global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend server'
    static_configs:
      - targets: ['<ip-address>:5000']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'Local Machine Node'
    static_configs:
      - targets: ['<ip-address>:9100']
